/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as FieldScanRouteImport } from './routes/field-scan'
import { Route as TalkRouteImport } from './routes/talk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldScanRoute = FieldScanRouteImport.update({
  id: '/field-scan',
  path: '/field-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/community': typeof CommunityRoute
  '/field-scan': typeof FieldScanRoute
  '/talk': typeof TalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/community': typeof CommunityRoute
  '/field-scan': typeof FieldScanRoute
  '/talk': typeof TalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/community': typeof CommunityRoute
  '/field-scan': typeof FieldScanRoute
  '/talk': typeof TalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/advisory' | '/community' | '/field-scan' | '/talk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/advisory' | '/community' | '/field-scan' | '/talk'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/community'
    | '/field-scan'
    | '/talk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  CommunityRoute: typeof CommunityRoute
  FieldScanRoute: typeof FieldScanRoute
  TalkRoute: typeof TalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-scan': {
      id: '/field-scan'
      path: '/field-scan'
      fullPath: '/field-scan'
      preLoaderRoute: typeof FieldScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  CommunityRoute: CommunityRoute,
  FieldScanRoute: FieldScanRoute,
  TalkRoute: TalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
